### PR TITLE
Update stem_emulator.user.js

### PR DESCRIPTION
**Pull request by vxkernel**
There was an added s what made it not able to connect

### CODE REVIEW

**Comment by jch254** [comment]
Yup this is it

**Comment by jch254** [comment]
Working fork here https://github.com/603dotnz/stem-player-emulator - just wanted to run it quickly

**Comment by nikkowalow** [comment]
on line 322 there was an extra 's' after the serial number which is didn't allow it to connect to stemplayer.com

**Comment by nikkowalow** [comment]
oh whoops someone already said that

**Comment by ThePussyDestroyer** [comment]
> Working fork here https://github.com/603dotnz/stem-player-emulator - just wanted to run it quickly

can you make a code so we can upload or link songs that we want to play in it please!?

**Pull request merged**
