### PR TITLE
Add iOS instructions

### PR DESCRIPTION
**Pull request by mmattbtw**

### CODE REVIEW

**Comment by mmattbtw** [comment]
C33697FB-D5F0-48D5-B0A5-3AFA430D3823

Screenshot of it working B)

**Comment by krystalgamer** [comment]
wtf, didn't know it worked on mobile lmao

**Comment by jch254** [comment]
Hey @mmattbtw did you manage to get audio playing out the iPhone speaker at all from the Stem Player site in safari?

**Comment by mmattbtw** [comment]
@jch254 yep! make sure to turn your ringer on, for some reason it wouldn't play with ringer muted :p

**Comment by jch254** [comment]
You are a wizard kind sir 🧙‍♀️ @mmattbtw 🙏🙏🙏

**Pull request merged**
